### PR TITLE
changed anchor serailze/deserailize to borsh

### LINKED ISSUE #1759: Anchor 0.30.1 build fails at pyth-solana-receiver-sdk 0.3.0 version
I'm using Anchor 0.30.1 version. I installed pyth-solana-receiver-sdk 0.3.0 version but build fails with this kind of errors.
```
error[E0599]: no function or associated item named `get_full_path` found for struct `MerklePriceUpdate` in the current scope
error[E0599]: no function or associated item named `create_type` found for struct `MerklePriceUpdate` in the current scope
error[E0599]: no function or associated item named `insert_types` found for struct `MerklePriceUpdate` in the current scope
```
Here is the full [error log](https://github.com/user-attachments/files/16139572/error.log).

### PR DESCRIPTION
**Pull request by mubarizkyc**
fix #1759 
I got the error 
Screenshot from 2024-07-13 16-20-45

On debugging i found out that it is originating for pythnet-sdk for src/wire.rs

Screenshot from 2024-07-13 16-24-12

issue : MerklePriceUpdate uses serde or Borsh while the the program was using Anchor, so i used borsh for s/dserailization

### CODE REVIEW

**Comment by guibescos** [comment]
Thanks for the contribution, can you please bump 
`pyth-solana-receiver-sdk` to `0.3.1` ?

**Comment by mubarizkyc** [comment]
@guibescos i didnt understand

**Comment by guibescos** [comment]
Please change the version of `pyth-solana-receiver-sdk` from `0.3.0` to `0.3.1`.
Also please fix the pre-commit checks.

**Comment by mubarizkyc** [comment]
@guibescos is it fixed now

**Review by guibescos — APPROVED** [review]

**Pull request merged**
