### PR TITLE
chore(target_chains/fuel): update fuel packages

### PR DESCRIPTION
**Pull request by martines3000**
This PR update fuel package versions for the Pyth Fuel JS SDK and the contracts project.

1. I added rust target `wasm32-unknown-unknown` as without it cargo `build` and `test` commands fail.
2. Slight implementation changes were made inside `contract_manager/src/contracts/fuel`. Without the changes the build process failed.

### CODE REVIEW

**Comment by martines3000** [comment]
@cctdaniel @ali-bahjati Please feel free to suggest/implement any changes you think are necessary.

**Comment by cctdaniel** [comment]
hi! thanks for your contribution, it seems like [no test cases were ran](https://github.com/pyth-network/pyth-crosschain/actions/runs/10495679788/job/29074625426?pr=1837#step:5:529) with this change which seems odd 🤔

**Comment by martines3000** [comment]
Hi. 
- `cargo test` was successful
- For the `forc test --verbose` command I looked at your other CI runs and there are also no tests run when it is executed. ([Example 1](https://github.com/pyth-network/pyth-crosschain/actions/runs/10078087593/job/27862175886) and [Example 2](https://github.com/pyth-network/pyth-crosschain/actions/runs/10105988557/job/27947383843))

**Comment by cctdaniel** [comment]
I see, thanks for pointing out the issue, we should have ran `cargo test` instead of `forc test`

**Review by cctdaniel — APPROVED** [review]
thank you for your contribution!

**Comment by martines3000** [comment]
I looked at the documentation and `forc test` is a wrapper around `cargo test`, but I am not sure why it doesn't run anything.
In my opinion, running `forc build`, `cargo test` and `cargo build` is enough to verify everything works as expected.

**Pull request merged**
